app:
    resource: "@AppBundle/Controller/"
    type:     annotation

repos_v1:
    type:     rest
    prefix:   /v1
    resource: AppBundle\Controller\v1\ReposController

repos_v2:
    type:     rest
    prefix:   /v2
    resource: AppBundle\Controller\v2\ReposController