repos_v1:
    type:     rest
    prefix:   /v1
    resource: AppBundle\Controller\v1\ReposController
    name_prefix:  v1_

repos_v2:
    type:     rest
    prefix:   /v2
    resource: AppBundle\Controller\v2\ReposController
    name_prefix:  v2_